### ISSUE TITLE
[Bug]: The URL returned during the authorization process was truncated

### ISSUE THREAD

**Issue by liuzhe1117** [VKCOM/vkid-ios-sdk#40]
### Описание проблемы

Since yesterday, some users have been unable to get authorization. The reason is that the URL returned by the authInWebView method is truncated. We can see that it only has 1023 or 1024 characters, which is not a complete JSON structure, so the parsing fails.

<img width="1399" alt="Image" src="https://github.com/user-attachments/assets/3a19e0b7-777c-4d68-a6b9-3579c58aa620" />

the url is :(1023 characters)

"vk52856552://vk.com/blank.html?payload=%7B%22type%22%3A%22silent_token%22%2C%22auth%22%3A1%2C%22user%22%3A%7B%22id%22%3A1036583701%2C%22first_name%22%3A%22Llllll%22%2C%22last_name%22%3A%22Z.%22%2C%22avatar%22%3A%22https%3A%2F%2Fsun6-22.userapi.com%2Fimpf%2FDW4IDqvukChyc-WPXmzIot46En40R00idiUAXw%2Fl5w5aIHioYc.jpg%3Fquality%3D96%26as%3D32x32%2C48x48%2C72x72%2C108x108%2C160x160%2C240x240%2C360x360%26sign%3D10ad7d7953daabb7b0e707fdfb7ebefd%26cs%3D200x200%22%2C%22avatar_base%22%3Anull%2C%22phone%22%3A%22%2B86%20***%20**%20**%20**%2096%22%7D%2C%22token%22%3A%225bQgdmigelNDOz8mIx-qFr6ukxJDIuymYyAfm1Ko_HKaOaCX22CDJHThahklerhH4Ib2Dqdmw0WZN2ggbzKidAZU9x5XlNPuDhThUnmMz_vuzCV6fI5GxIWojvU5sDeVcQCDTLae6ThApg9vMlzJfYuwFOQV-FyLjK-ekUTco7UidXjzUwxaE0LTvYAjyOg9dBsjh6qVRl_ETsez4aeS2Mj1T1-LN7XJeOK8XdzqVoGCk75XVAoE3plh7m9RPhqhoMT-79RbjlU-j70sZE91A9Wv_h6WQOpfHqh-nDis5C1wrQ8b0GHTeEzXQU9BiM5Fw5zTQ7b0HbRgfyq1iJuVhq2KMJ7fvdCHuNPIfSxQSBAoe5vjPNcZ0pmGk3ZakRz0DAMXIhJ-3Av9dTzeolu0Ka9C1LimRFbeaGSshX7OK-s%22%2C%22ttl%22%3A600%2C%22uuid%22%"

after url decoded is:

vk52856552://vk.com/blank.html?payload={"type":"silent_token","auth":1,"user":{"id":1036583701,"first_name":"Llllll","last_name":"Z.","avatar":"https://sun6-22.userapi.com/impf/DW4IDqvukChyc-WPXmzIot46En40R00idiUAXw/l5w5aIHioYc.jpg?quality=96&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360&sign=10ad7d7953daabb7b0e707fdfb7ebefd&cs=200x200","avatar_base":null,"phone":"+86 *** ** ** ** 96"},"token":"Btw9WXwPN3GzMbm3WB7nNUjbJcRin1lGG50xegTu7JcxdfCn90sqcRL4oSjlLiYtNqQzPpbKk_T5HAdLpvfuhn6CXrBBEaaXg6Xiru6en4OniHEWX8Mtf1N6OW0l2DaISUPxJSc1k6ab9VeauU-zauRM8kskRfi1AG9Tt1Nwoi1WaMFAxbnKhtKcqAnS1Sqyng1bmsxZDEEOKDzexRZX__W8hQr-N1iqfRxse8VCWcOqF0uhJi60Gkvm1xR5TABkvvvlDhrDPMuYJgfURrcyNNPXdib3HBhcT1Tqk2uKttHeR2H7WJHGx96mirAA6eI-2ny595vEC70y2fgK2ZSkNJO1V37cV8ZnCgNuNdP6-KOBIE_7Qf3YNxQs_VkiCEFRsKdTh2VInDsDD7ZNDgCF5cPkMOD4p1ot1T8aOHtS4rM","ttl":600,"uuid"%

Obviously, some content is missing. Please check for any recent server updates.

The old vksdk is not affected.

### Версия VK ID SDK

1.3.3

### Способ установки

CocoaPods

### Версия Xcode

16.2

### Версия iOS

15.7.2

**Comment by player-man** [comment]
Hello! We noticed in old versions occurring issues. It was fixed already. You can update SDK to the latest versions 2.x.x to ignore the issues kinda like that.

**Comment by liuzhe1117** [comment]
> Hello! We noticed in old versions occurring issues. It was fixed already. You can update SDK to the latest versions 2.x.x to ignore the issues kinda like that.

Version 2.x.x is based on Oauth 2.1 and does not support implicit grant. 
Version 1.x.x is based on Oauth 2.0 and supports implicit grant. 

We think you are maintaining two series independently instead of an upgrading relationship. Because some scenarios also require support for implicit grant. The cost of converting from implicit grant to authorization code grant is very high.

In addition, version 1.x.x has been able to be used normally until May 12, when the return packet was truncated. I believe that this must be some kind of upgrade on the server that day (the client SDK has not changed at all), and it only needs to be rolled back.

**Comment by liuzhe1117** [comment]
The issue still exists


But we found that one way can successfully authorize, and the other way will fail.

The fail way:
https://github.com/user-attachments/assets/8154705d-ef28-46d8-b809-2a35d5e166da

Payload parameter in the returned URL:
`
{
	"type":"silent_token",
	"auth":1,
	"user":{
		"id":1036583701,
		"first_name":"Llllll",
		"last_name":"Z.",
		"avatar":"https://sun6-23.userapi.com/s/v1/ig2/cF79IYenxawHBEZOGN8dMA7y6hVmtnazpw7gW0QkqxFmlBDkSBgG4H321jeeONCPDwUxLEgC6nwzMpMQRz-Xn7L3.jpg?quality=95&crop=0,0,720,720&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720&ava=1&cs=200x200",
		"avatar_base":null,
		"phone":"+86 *** ** ** ** 96"
	},
	"token":"mx5fV6J8LBv44d8GWHMNEj0ch_it7gxOlWLlbDqkQwakosL0Xcbl8uUljTN9Kdh3RE7Z7znK0jk_eSYrS37ry8Pq1EUmIcFPL6coQ5CnYK4DqQo3khODtndr5XiDroDoCt7yHnJllS2YyHxl5S8ulHs_gHHPxS3teGAxn4Ov2iG3jlfmoOtlhPUuhnsW6Q9gAcCW5UFZVr2e7bDS6JCyf8zO40xrY2vfcgbKe6Z2WV4XrwHWzOG-hK8d9WZAjDYjw8a2Q5OYmb1O6_cnOhulHvsHBIk24v2gFzGiht4eiDlgXUwOJ-Rz_Ut3V-hczsggpY9myk5GGUH5ZlOuRUZ2zZpY4pds1GN5oO-fKcwBgPkVIVh4EohCRguk1McaWKL
`

![Image](https://github.com/user-attachments/assets/fb86ef2d-7fe1-45d6-82a7-2f8b29137e9c)


The success way:
https://github.com/user-attachments/assets/f639d311-07d5-4389-a475-72e0a3740f6a

Payload parameter in the returned URL:（truncated）
`{
	"type":"oauth",
 	"auth":1,
 	"user":{
		"id":1036583701,
		"first_name":"Llllll",
		"last_name":"Z.",
		"avatar":"https:\/\/sun6-23.userapi.com\/s\/v1\/ig2\/cF79IYenxawHBEZOGN8dMA7y6hVmtnazpw7gW0QkqxFmlBDkSBgG4H321jeeONCPDwUxLEgC6nwzMpMQRz-Xn7L3.jpg?quality=95&crop=0,0,720,720&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720&ava=1&cs=200x200",
		"avatar_base":null,
		"phone":"+86 *** ** ** ** 96"
	},
	"ttl":600,
	"uuid":"",
	"hash":"1EnKHmkrGdw7zO700pkOZhCO3y7jAz57B5ujLI4XXqH",
	"oauth":{
		"code":"db16194aee7b810a85",
		"state":"B7CDC158-00A5-4872-9F60-B661560775F7",
		"oauth_response_type":"code",
		"oauth_code_challenge":"",
		"oauth_code_challenge_method":""
	}
}`

![Image](https://github.com/user-attachments/assets/84410515-c929-4c40-b3ee-8929b3c62186)
